# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=false
org.gradle.caching.debug=false
#org.gradle.parallel=false
#org.gradle.configureondemand=true

# Needed to use newer libraries while architectury loom is not up-to-date
loom.ignoreDependencyLoomVersionValidation=true

# Mod properties
mod.version=1.12.1
mod.group=eu.midnightdust
mod.id=midnightcontrols
mod.name=MidnightControls

# Used for the mod metadata
mod.mc_dep_fabric=[VERSIONED]
mod.mc_dep_forgelike=[VERSIONED]
# Used for the release title. I.e. '1.20.x'
mod.mc_title=[VERSIONED]
# Space separated versions for publishing. I.e. '1.20, 1.20.1'
mod.mc_targets=[VERSIONED]

# Mod setup
deps.fabric_loader=0.18.2
deps.fabric_version=[VERSIONED]

deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]
deps.neoforge_patch=[VERSIONED]

# Mod dependencies
deps.midnightlib_version=1.9.3

# Integrations
deps.sodium_version=mc1.21.11-0.8.2
deps.spruceui_version=9.1.0+1.21.11
deps.yumimc_version=1.0.0-beta.1+1.21.11
deps.modmenu_version=10.0.0-beta.1
deps.emotecraft_version=3.2.0-b.build.134
deps.bendylib_version=2.0.+
deps.emi_version=1.1.22+1.21.1
deps.libgui_version=6.0.0+1.19
deps.inventorytabs_version=inventorytabs-0.9.beta-1.19.x
deps.clothconfig_version=7.0.72
deps.yacl_version=3.8.1
deps.bedrockify_version=1.9+mc1.20

# Publishing
publish.modrinth=bXX9h73M
publish.curseforge=621768
