mod.mc_dep_fabric=>=26.2
mod.mc_dep_forgelike=[26.2,)
mod.mc_title=26.2
mod.mc_targets=26.2

deps.forge_loader=0
deps.neoforge_loader=26.2.0.37-beta

deps.fabric_version=0.156.0+26.2
deps.modmenu_version=20.0.1
deps.sodium_version=mc26.2-0.9.1
deps.spruceui_version=11.0.0+26.2
deps.yumimc_version=1.1.1+26.2
deps.yacl_version=3.9.6
deps.emotecraft_version=3.4.0-b.build.161
deps.libgui_version=17.0.0+26.2
