mod.mc_dep_fabric=>=26.1
mod.mc_dep_forgelike=[26.1,)
mod.mc_title=26.1
mod.mc_targets=26.1

deps.forge_loader=0
deps.neoforge_loader=26.1.0.1-beta

deps.fabric_version=0.144.1+26.1
deps.modmenu_version=18.0.0-alpha.6
deps.sodium_version=mc26.1-0.8.7
deps.spruceui_version=10.0.0+26.1
deps.yumimc_version=1.0.0-beta.2+26.1
deps.yacl_version=3.9.1
deps.emotecraft_version=3.3.0-a.build.148+26.1-fabricneo
deps.libgui_version=16.0.1+26.1

loom.platform=fabric
