name: Publish to Modrinth & CurseForge

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          check-latest: true
      # The USERNAME and PASSWORD need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to GitHub Packages and other Mavens
        run: ./gradlew publish
        env:
          BRANCH_NAME: ${{ github.ref }}
          RUN_COUNT: ${{ github.run_number }}
          REPO_NAME: ${{ github.repository }}
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          midnightcontrols_MAVEN: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Publish to Modrinth and CurseForge
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        run: ./gradlew publishMods
